// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface FaqItem {
  id: string;
  slug: string | null;
  status: string;
  question: string;
  answer: string;
  category?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number };
  content?: PortableTextBlock[];
  excerpt?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface ProcessStep {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  duration?: string;
  step_order?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Service {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  description?: string;
  price?: number;
  diagnostic_price?: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    faq: FaqItem;
    pages: Page;
    posts: Post;
    process_steps: ProcessStep;
    services: Service;
  }
}